[workspace]
authors = ["EnderRieck <junjun20050801@126.com>"]
channels = ["conda-forge"]
name = "backend"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
requests = ">=2.32.5,<3"
rich = ">=14.2.0,<15"
openpyxl = ">=3.1.5,<4"

[pypi-dependencies]
fastapi = ">=0.127.0, <0.128"
uvicorn = ">=0.40.0, <0.41"
sqlmodel = ">=0.0.29, <0.0.30"
sqlalchemy = ">=2.0.45, <3"
pydantic = ">=2.12.5, <3"
pyyaml = ">=6.0.3, <7"
python-socketio = ">=5.16.0, <6"
httpx = ">=0.28.1, <0.29"
